### ISSUE TITLE
Allow omitting OID name/description

### ISSUE THREAD

**Issue by pkolbus** [ARMmbed/mbed-crypto#134]
### Description

On small systems (e.g. Cortex-M4) every KB of code footprint counts, and the OID name and description string tend to only be needed in certain debugging/tools contexts (e.g. `mbedtls_x509_crt_info()`). I've noticed that when building with `-ffunction-sections`, `-fdata-sections`, and `gc-sections`, there are a few KB of wasted code space because constant strings are entangled to types in a way that makes it hard for a linker to omit them.

I have a similar approach in mind as https://github.com/ARMmbed/mbedtls/pull/2315, and propose the configuration `MBEDTLS_OID_NAMES`. If you agree I can get started on the PR.

Note that because mbed TLS now uses mbed-crypto, this issue is a dependency for that PR.

### Issue request type

    [ ] Question
    [X] Enhancement
    [ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-787*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by gilles-peskine-arm** [comment]
This will finally be resolved through https://github.com/Mbed-TLS/mbedtls/issues/9379 in TF-PSA-Crypto 1.0 and Mbed TLS 4.0.
