### ISSUE TITLE
Supply a Docker image for test execution

### ISSUE THREAD

**Issue by pkolbus** [ARMmbed/mbed-crypto#135]
### Description

The test scripts (especially `all.sh`) have a number of dependencies. Supplying a Dockerfile and helper scripts would make it easier for contributors (running Linux at least) to set up a complete environment for running tests.

https://github.com/ARMmbed/mbedtls/pull/2314 provides a good basis for this. 

### Issue request type

    [ ] Question
    [X] Enhancement
    [ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-786*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by hug-dev** [comment]
For future reference, as I came up to this issue when wanting to add a Mbed Crypto container for our own project, the following Dockerfile will install Mbed Crypto version `2.0.0` in `/tmp/` inside the container:

```
FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y make gcc python3 python wget

WORKDIR /tmp
RUN wget https://github.com/ARMmbed/mbed-crypto/archive/mbedcrypto-2.0.0.tar.gz
RUN tar xf mbedcrypto-2.0.0.tar.gz
RUN cd mbed-crypto-mbedcrypto-2.0.0 \
		&& make
```

**Comment by gilles-peskine-arm** [comment]
The Docker images that the maintainer team uses are now publicly available in https://github.com/Mbed-TLS/mbedtls-test/tree/master/resources/docker_files
