### ISSUE TITLE
When used as a submodule, PSA source files pick up the wrong config.h

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbed-crypto#141]
### Description

When Mbed Crypto is used as a submodule in Mbed TLS, only the `config.h` of Mbed TLS should be used. But PSA source files use the ones in the submodule.

Steps to reproduce:
```
git clone https://github.com/ARMmbed/mbedtls
cd mbedtls
git submodule update
rm crypto/include/mbedtls/config.h
make
```

Expected behavior: since Mbed Crypto is used as a submodule in Mbed TLS, the `config.h` file under `crypto` should not be used.

Actual behavior:
```
…
  CC    psa_crypto.c
In file included from ../include/psa/crypto.h:25:0,
                 from psa_crypto.c:31:
../include/psa/crypto_platform.h:41:31: fatal error: ../mbedtls/config.h: No such file or directory
compilation terminated.
Makefile:146: recipe for target 'psa_crypto.o' failed
make[2]: *** [psa_crypto.o] Error 1
Makefile:152: recipe for target 'libmbedcrypto.a' failed
make[1]: *** [libmbedcrypto.a] Error 2
Makefile:19: recipe for target 'lib' failed
make: *** [lib] Error 2
```

Validation: to make sure that the wrong `config.h` is not used, we should do a build where its contents are replaced by something that will cause a build error, e.g. `#barf`.

### Issue request type

    [ ] Question
    [ ] Enhancement
    [x] Bug

**Comment by Patater** [comment]
`#include "../mbedtls/config.h"` shouldn't be used. Use `#include "mbedtls/config.h` instead, so that the submodule-building makefiles can change which directory to use to get mbedtls include files from.
