### ISSUE TITLE
Double-underscore in macro names is not valid in C++

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbed-crypto#171]
### Description

Mbed Crypto headers define an identifier that is reserved in C++. Specifically `PSA__ALG_AEAD_WITH_DEFAULT_TAG_LENGTH__CASE` in `include/psa/crypto_values.h`. C++ reserves double underscores.

Note that it isn't enough to just change the double underscore to a single underscore: `test_psa_constant_names.py` picks up macros `PSA_ALG_.*` and would need to skip this one somehow. See https://github.com/ARMmbed/mbedtls-psa/pull/258 (private link).

Acceptance criteria:

* Add a check for double underscores. To `check-names.sh`, presumably. It already checks for trailing underscores, for whatever reason.
* Obviously, make the check pass without breaking anything else.

### Issue request type

    [ ] Question
    [ ] Enhancement
    [x] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-826*

**Comment by AndrzejKurek** [comment]
PR created: https://github.com/ARMmbed/mbed-crypto/pull/230

**Comment by gilles-peskine-arm** [comment]
Fixed by https://github.com/ARMmbed/mbed-crypto/pull/230
