### ISSUE TITLE
Test that PSA headers work in C++

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbed-crypto#172]
### Description

We test that Mbed TLS headers are compatible with C++. We only test `include/mbedtls/*.h`. We should also test `include/psa/*.h`.

### Issue request type

    [ ] Question
    [x] Enhancement
    [ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-825*

**Comment by gilles-peskine-arm** [comment]
Done in https://github.com/Mbed-TLS/mbedtls/pull/3814.
