### ISSUE TITLE
psa_mac_compute doesn't have PSA_ERROR_BUFFER_TOO_SMALL error code

### ISSUE THREAD

**Issue by gowthamsiddarthd** [ARMmbed/mbed-crypto#177]
### Description

Version: psa-crypto-api-1.0-beta
API: psa_mac_compute

One of the parameters of this function is mac_size. The specification doesn't mention about returning PSA_ERROR_BUFFER_TOO_SMALL when the mac_size is less than the actual required size.

### Issue request type

    [ ] Question
    [x] Enhancement
    [ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-829*

**Comment by adrianlshaw** [comment]
Should be fixed in #213

**Comment by Patater** [comment]
#213 has been merged. Closing as fixed.
