### ISSUE TITLE
Doxygen can't seem to link to MBEDTLS_PARAM_FAILED

### ISSUE THREAD

**Issue by Patater** [ARMmbed/mbed-crypto#195]
# Description

In #187, in `include/mbedtls/config.h`, we changed `#MBEDTLS_PARAM_FAILED` to `MBEDTLS_PARAM_FAILED` to get `doxygen.sh` to pass. Given that this link works in Mbed TLS, it's odd that it doesn't also work in Mbed Crypto. Why not?

We've reviewed the `doxygen/mbedtls.doxyfile` and `include/mbedtls/config.h` in both repos and don't yet see why this link should work in one but not the other. We should be able to link to #MBEDTLS_PARAM_FAILED in Mbed Crypto.

### Issue request type
    [ ] Question
    [ ] Enhancement
    [X] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-841*

**Comment by gilles-peskine-arm** [comment]
`MBEDTLS_PARAM_FAILED` is no longer in the development version of Mbed TLS. It's still present in 2.28 LTS, but this is a minor documentation issue and we aren't going to work on it only for the sake of an LTS version.
