### ISSUE TITLE
Implement custom RSA public exponent for keys in secure elements

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbed-crypto#216]
### Description

In `psa_get_key_attributes`, reporting the domain parameters for a key in a secure element is not implemented. Specifically, we're supposed to report the public exponent of an RSA key, so that `psa_get_key_attributes` on a key followed by `psa_generate_key` creates a key with the same public exponent as the first key.

### Issue request type

    [ ] Question
    [x] Enhancement
    [ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-864*

**Comment by gilles-peskine-arm** [comment]
The secure element driver interface enabled by `MBEDTLS_PSA_CRYPTO_SE_C` is deprecated. We will add new features to it.

The same issue applies to the new “unified” driver interface, but also to the PSA API, since we have removed the ability to randomly generate an RSA key with a custom public exponent. Since the driver interface now follows the API, if we add this possibility to the API, we will also add it to the driver interface.
