### ISSUE TITLE
Implement secure element operations

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbed-crypto#219]
### Description

Implement and test cryptographic operations using keys in a secure element. At the moment, the only supported operations are import, generate, sign, verify, export, export public, destroy, open, close. Even these operations are only lightly tested.

### Issue request type

    [ ] Question
    [x] Enhancement
    [ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-861*

**Comment by gilles-peskine-arm** [comment]
The secure element driver interface enabled by `MBEDTLS_PSA_CRYPTO_SE_C` is deprecated. We will not add new features to it.
