### ISSUE TITLE
Automate on-target testing

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbed-crypto#249]
### Description

As a developer or maintainer of Mbed Crypto/TLS,
I want `mbedtls_test.py` to be validated by the CI
so that I'm confident that changes to this file work.

Add automation for on-target testing: building the test suites and running them with `mbedtls_test.py`. Run this automation on the CI.

### Issue request type

    [ ] Question
    [x] Enhancement
    [ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-890*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by gilles-peskine-arm** [comment]
`mbedtls_test.py` [no longer exists](https://github.com/Mbed-TLS/mbedtls/pull/5116), so this issue is moot. We plan to design a replacement mechanism, and when we do, ease of use (without a long chain of manual steps) will be a primary consideration.
