### ISSUE TITLE
Duplicate test case descriptions

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbed-crypto#262]
### Description

We have 1420 duplicated test case descriptions, i.e. two test cases in the same test suite that have the exact same description.

This doesn't break any tooling yet, but it makes the outcome file introduced by https://github.com/ARMmbed/mbedtls/pull/2843 imprecise. It also makes it hard to figure out which test case is failing when looking at logs.

https://github.com/ARMmbed/mbedtls/pull/2843 adds a script `tests/scripts/check-test-cases.py` that checks this issue and fixes the problem in the tests that are present in `mbedtls/development`.

### Issue request type

    [ ] Question
    [ ] Enhancement
    [x] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-916*

**Comment by gilles-peskine-arm** [comment]
The scope of this issue is solely to make test case descriptions unique. Making them correct and helpful is out of scope. Reviewing the correctness of the non-unique test descriptions is in scope for https://github.com/ARMmbed/mbed-crypto/issues/271.
