### ISSUE TITLE
Occupy bits in struct psa_key_derivation_s

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbed-crypto#281]
### Description

https://github.com/ARMmbed/mbed-crypto/pull/276 introduced a 1-bit field in `struct psa_key_derivation_s`. We can use 31 more bits for flags or more generally small values that are currently in type-specific parts of the union, e.g. for state data that applies to most KDFs. This would save a tiny amount of RAM (and perhaps code size if the moved stuff is currently at a large offset that requires larger code to access).

### Issue request type

    [ ] Question
    [x] Enhancement
    [ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-938*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by gilles-peskine-arm** [comment]
With the introduction of the driver interface, this lone bit no longer seems to have potential companions.
