### ISSUE TITLE
Allow SE drivers to return the public key when generating a key pair

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbed-crypto#282]
### Description

In the PSA secure element driver interface, the method `psa_drv_se_generate_key_t   p_generate` optionally returns the public key. This capability is not implemented in Mbed Crypto yet. Implement it: provide a large enough buffer, and store the public key in ITS.

### Issue request type

    [ ] Question
    [x] Enhancement
    [ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-941*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by gilles-peskine-arm** [comment]
The secure element driver interface enabled by `MBEDTLS_PSA_CRYPTO_SE_C` is deprecated. We will not add new features to it.
