### ISSUE TITLE
Allow passing the public key when registering a key in a secure element

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbed-crypto#283]
### Description

`mbedtls_psa_register_se_key` allows registering a key which is already present in a secure element. The caller passes metadata such as the location, key type and usage policy.

For secure elements that can't export the public key from a private key slot, key registration needs to let the caller pass the public key. Related: #282 for key generation.

### Issue request type

    [ ] Question
    [x] Enhancement
    [ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-940*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by gilles-peskine-arm** [comment]
The secure element driver interface enabled by `MBEDTLS_PSA_CRYPTO_SE_C` is deprecated. We will not add new features to it.
