### ISSUE TITLE
MBEDTLS_CTR_DRBG_USE_128_BIT_KEY is not tested

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbed-crypto#289]
### Description

`MBEDTLS_CTR_DRBG_USE_128_BIT_KEY` is not tested on our CI. Since it's in the "Module configuration options" section of `config.h`, `config.pl full` does not set it. It isn't in any reference configuration in `configs` and isn't enabled by any component of `all.sh`.

### Issue request type

    [ ] Question
    [x] Enhancement
    [ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-946*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.
