### ISSUE TITLE
The selftest program fails with MBEDTLS_CTR_DRBG_USE_128_BIT_KEY

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbed-crypto#290]
### Description

Steps to reproduce:
```
scripts/config.pl set MBEDTLS_CTR_DRBG_USE_128_BIT_KEY
make
programs/test/selftest ctr_drbg
```

Expected behavior: `passed`

Actual behavior: `failed`

Reason for the failure: we only have test data with AES-256, not with AES-128.

Reasons this was not detected before:
* We normally run self-tests as part of the test suite, but the test case in `test_suite_ctr_drbg.data` has `depends_on:!MBEDTLS_CTR_DRBG_USE_128_BIT_KEY`, so the selftest is skipped when using AES-128. No such skipping happens in the selftest program.
* Even if we did run the selftests from the test suite, we don't actually enable `MBEDTLS_CTR_DRBG_USE_128_BIT_KEY` anywhere in `all.sh` (https://github.com/ARMmbed/mbed-crypto/issues/289).

How I detected this: in https://github.com/ARMmbed/mbed-crypto/pull/287 I moved `MBEDTLS_CTR_DRBG_USE_128_BIT_KEY` to the `mbed TLS feature support` section where it belongs, so it got picked up by `config.pl full`. We do run `selftest` in that configuration on the CI, albeit only on Windows.

### Issue request type

    [ ] Question
    [ ] Enhancement
    [ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-945*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.
