### ISSUE TITLE
Test a build with only symmetric cryptography

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbed-crypto#296]
### Description

We have no build with only symmetric cryptography anywhere in `all.sh`. In particular, we never build with `MBEDTLS_BIGNUM_C` disabled, which happens in the real world either when building with no asymmetric cryptography or when all the asymmetric cryptography comes from ALT implementations that don't use any bignum functions.

This could cause the mbedtls configuration [`config-ccm-psk-tls1_2.h`](https://github.com/ARMmbed/mbedtls/blob/development/configs/config-ccm-psk-tls1_2.h) to fail. As of 9ab7c07f1f370636fcaa8bc02e6f45035fab1596, mbed-crypto builds and passes TLS tests with `config-ccm-psk-tls1_2.h`, but the `test_suite_asn1parse` fails to build when `MBEDTLS_ASN1_PARSE_C` is enabled but `MBEDTLS_BIGNUM_C` is disabled.

We can't test every possible combination of build options, but we should test at least one configuration without the bignum module. I propose to test with all features that don't depend on `MBEDTLS_BIGNUM_C`.

### Issue request type

    [ ] Question
    [x] Enhancement
    [ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-951*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.
