### ISSUE TITLE
Import EC private key is rejected as key length mis-match

### ISSUE THREAD

**Issue by CharleyChu** [ARMmbed/mbed-crypto#331]
Call psa_import_key() to import an ASN1 encoding of ECP256R1 private key. It is rejected as following check failed in psa_import_key_into_slot()

  if( PSA_BITS_TO_BYTES( PSA_ECC_CURVE_BITS( curve ) ) != data_length )
        return( PSA_ERROR_INVALID_ARGUMENT );

The expect length is 32 for ECP256R1, but the actually key length (data_lenght) is 33 as a leading 00 is added for the DER representation of positive integers

   [ ] Question
    [ ] Enhancement
    [x ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-1020*

**Comment by gilles-peskine-arm** [comment]
Hi @CharleyChu,

`psa_import_key` expects the raw private key, not an ASN.1 encoding. For a P256R1 key, the raw private key is always 32 bytes, no matter how many leading zero bits are present.

If you have the key in an ASN.1 encoding, you'll need to convert it. Mbed Crypto can import keys in the format defined in RFC 5915 with `mbedtls_pk_parse_key()`, then you can obtain a `mbedtls_ecp_keypair*` with `mbedtls_pk_ec()` and use `mbedtls_mpi_write_binary(mbedtls_pk_ec(pk)->d, buf, 32)` to extract the private key. We intend to provide more convenient parsing functions in a future version of Mbed Crypto.

**Comment by CharleyChu** [comment]
Thanks Gilles!
