### ISSUE TITLE
Recent doxygen throws warnings "return value XXX of xxx has multiple documentation sections"

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbed-crypto#359]
### Description

When running `tests/scripts/doxygen.sh` with doxygen 1.8.17, the script fails with a bunch of warnings, in particular there are 48 warnings looking like
```
warning: return value '#PSA_XXX' of psa_xxx has multiple documentation sections
```

This issue is about those warnings (other warnings thrown by doxygen 1.8.17 are tracked in other issues: #356 and #360).

### Issue request type

    [ ] Question
    [ ] Enhancement
    [x] Bug

**Comment by gilles-peskine-arm** [comment]
This was deliberate: I used `\retval FOO` twice if there were two error conditions that led to the same return value. There's nothing in the [documentation](http://www.doxygen.nl/manual/commands.html#cmdretval) to say that this isn't the normal way to use it :frowning_face:

**Comment by mpg** [comment]
If this is deliberate, perhaps there's a way to turn the warning off in the doxyfile?

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-1045*

**Comment by gilles-peskine-arm** [comment]
Let's continue this in https://github.com/ARMmbed/mbedtls/issues/3497
