### ISSUE TITLE
Doxygen 1.8.17 throws warnings about our doxyfile

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbed-crypto#360]
### Description

When running tests/scripts/doxygen.sh with doxygen 1.8.17, the script fails with a bunch of warnings, in particular there are 2 warnings about our doxyfile:

```
Tag 'MSCGEN_PATH' at line 1713 of file 'mbedtls.doxyfile' has become obsolete.
Tag 'PERL_PATH' at line 1692 of file 'mbedtls.doxyfile' has become obsolete.
```

This issue is specifically about those warnings (other warnings thrown by doxygen 1.8.17 are tracked in other issues: #356 and #359).

### Issue request type

    [ ] Question
    [ ] Enhancement
    [x] Bug

**Comment by gilles-peskine-arm** [comment]
Our doxyfile is the default doxyfile from some past doxygen version, with some options modified to suit our project. We should replace that by a doxyfile that only mentions the options that we want to modify from the default.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-1044*

**Comment by mpg** [comment]
Let's continue this in ARMmbed/mbedtls#3497
