### ISSUE TITLE
Don't use FindPythonInterp

### ISSUE THREAD

**Issue by okhowang** [ARMmbed/mbed-crypto#389]
### Issue request type

    [ ] Question
    [x] Enhancement
    [ ] Bug

see [https://cmake.org/cmake/help/latest/module/FindPythonInterp.html](https://cmake.org/cmake/help/latest/module/FindPythonInterp.html)
FindPythonInterp may failed when python 2 found first

**Comment by gilles-peskine-arm** [comment]
Note that we do want to maintain backward compatibility with somewhat older versions of cmake, at least cmake 3.5.1 which is the version of Ubuntu 16.04. So we can't just switch to `FindPython3` or `FindPython`.

**Comment by okhowang** [comment]
can we add a progressive upgraded behaviour?
for example if cmake version > 3.x do `FindPython3` instead of `FindPythonInterp`

**Comment by gilles-peskine-arm** [comment]
Sure. As long as the file can be parsed with older versions, that's ok. We have tests on `GCC_VERSION`, we can have tests on `CMAKE_VERSION` as well (or on `cmake_is_module_available("FindPython3")` if there's such a thing?).
