### ISSUE TITLE
Zero length keys not supported when generating persistent keys

### ISSUE THREAD

**Issue by dgreen-arm** [ARMmbed/mbed-crypto#50]
### Description

`psa_save_generated_persistent_key` does not support zero-length keys on all platforms. This has been missed due to not having a test for zero-length raw keys. 

### Issue request type

    [ ] Question
    [ ] Enhancement
    [x] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-671*
