### ISSUE TITLE
psa_cipher_setup leaves operation in partially initialized state in case of error

### ISSUE THREAD

**Issue by NirSonnenschein** [ARMmbed/mbed-crypto#68]
### Description

in some of the setup functions the operation structure is not properly cleaned up in case of failure.
we specifically encountered this in the psa_cipher _setup. When passing in an invalid key handle (with other valid parameters) it will fail but leave the operation structure with the algorithm set.
This is OS and platform independent behavior.

Note: this likely also impacts other setup functions (e.g. psa_hmac_setup_internal, psa_mac_setup, etc..)

### Issue request type

    [ ] Question
    [ ] Enhancement
    [X] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-701*

**Comment by gilles-peskine-arm** [comment]
Fix for cipher in #72. By code inspection, the MAC code looks correct to me (`psa_mac_init` either succeeds or reinitializes the context, and `psa_mac_setup` reinitializes the context on failure if `psa_mac_init` has succeeded).
