### ISSUE TITLE
Test ASN.1 in Mbed Crypto

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbed-crypto#76]
### Description

ASN.1 is mostly tested through X.509 and TLS. With the separation between Mbed Crypto and Mbed TLS, the ASN.1 modules end up in Mbed Crypto but they're barely tested there. It would be useful to test them.

### Issue request type

    [ ] Question
    [x] Enhancement
    [ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-720*
