### ISSUE TITLE
psa_key_agreement doesn't check the generator is not active

### ISSUE THREAD

**Issue by itayzafrir** [ARMmbed/mbed-crypto#88]
### Description
API `psa_key_agreement` does not check that the `generator` object is not active.
I think a check similar to the check in `psa_key_derivation` is missing:
```
if( generator->alg != 0 )
    return( PSA_ERROR_BAD_STATE );
```

### Issue request type

    [ ] Question
    [ ] Enhancement
    [x] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-750*
