### ISSUE TITLE
Document the stability of PSA interfaces

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbed-crypto#93]
### Description

As the PSA interfaces are stabilizing, we should document what we'll maintain backward compatibility for and what we won't.

* Public APIs that haven't completely stabilized yet, but we'll provide a short transition period if we make changes: `include/crypto/crypto.h`, `include/crypto/crypto_types.h`, `include/crypto/crypto_values.h` (only the macros that have Doxygen documentation), `include/crypto/crypto_extra.h`. We should also note that even if the interfaces stabilize, that doesn't mean that the implementation is production-quality yet.
* Internal definitions that are platform-dependent and may change without notice: `include/crypto/crypto_platform.h`, `include/crypto/crypto_struct.h`
* File storage for persistent keys
* Driver HAL: not stable yet.

Where to document it: in the comment at the top of each header, in `README.md`, in the Doxygen documentation, …

### Issue request type

    [ ] Question
    [x] Enhancement
    [ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCRYPT-754*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by gilles-peskine-arm** [comment]
The PSA interfaces have stabilized so this is moot.
